image:
  repository: eu.gcr.io/pulr-kubernetes/pulr-promotion
  tag: 0.0.7
  pullPolicy: IfNotPresent

web:
  replicas: 1
  port: 80
  healthcheck: /
  initializationCommand:
    - nginx
    - -g
    - daemon off
  memoryLimit: 512
  cpuLimit: 500

hosts:
  - 'promotion.pulr.tk'
